In [24]:
import pandas as pd

df = pd.read_csv(r"C:\Users\MOIZ\DeepLearning\microProject2\IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [25]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [26]:
df.drop_duplicates(inplace=True)

Pre Processing

1] Convert to lowercase

In [27]:
df["review"] = df["review"].str.lower()

In [28]:
import re # regular expression
#regix library

In [29]:
def remove_urls(text):
    text = re.sub(r"http\S+","",text) #(pattern,repl,string)
    return text
df["review"] = df["review"].apply(remove_urls)

Remove Punctuation

In [30]:
def remove_punctuations(text):
    text = re.sub(r"[^A-za-z0-9\s]","",text)
    return text

df["review"] = df["review"].apply(remove_punctuations)

Removing HTML

In [31]:
def remove_html(text):
    text = re.sub(r"<.*?>","",text)
    return text

df["review"] = df["review"].apply(remove_html)

In [34]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")


    for word in tokens:
        if word in stop_words:
            text=text.replace(word,"")

    return text
df["review"] = df["review"].apply(remove_stopwords)

Steming

In [38]:
from nltk.stem import PorterStemmer
def stemming(text):
    ps = PorterStemmer()
    stemmed_words =[]
    
    tokens = word_tokenize(text)
    for token in tokens:
        stemmed_token = ps.stem(token)
        stemmed_words.append(stemmed_token)
    return " ".join(stemmed_words)
df["review"] = df["review"].apply(stemming)

Encoding

In [40]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["sentiment"] = le.fit_transform(df["sentiment"])

In [43]:
y = df["sentiment"]

In [44]:
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

In [45]:
df.head()

                                              review  sentiment
0  e revew nted wtchg 1 oz epod ll hook y rght ex...          1
1  wder ltle producti br br film techniqu unssum ...          1
2  thought th wder wy spend tme o hot summer week...          1
3  bsclli re fmli lttle boy jke thk re zomb close...          0
4  petter mtte love time mey vulli stunng film wt...          1

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(max_features=5000)
X = tf.fit_transform(df["review"])

In [47]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4054738 stored elements and shape (49582, 5000)>

In [48]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4054738 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 3537)	0.055172586141150226
  (0, 2866)	0.09360715313699464
  (0, 4940)	0.11471517555103908
  (0, 3000)	0.4719818270486242
  (0, 1276)	0.13576311159915805
  (0, 2288)	0.049511010686691684
  (0, 1932)	0.07912207930050451
  (0, 3549)	0.0964617216417389
  (0, 1361)	0.061646058918606104
  (0, 1961)	0.06155737067674403
  (0, 220)	0.08588300923323462
  (0, 1619)	0.07386441987591297
  (0, 4367)	0.04201440342897208
  (0, 4169)	0.17809913659698137
  (0, 3692)	0.033559596604044846
  (0, 4737)	0.26797604590397783
  (0, 3804)	0.04430009216877035
  (0, 4769)	0.05877112365001594
  (0, 1738)	0.037507181147532515
  (0, 4495)	0.07613686094268304
  (0, 3856)	0.17546267791412257
  (0, 1629)	0.061429350281813636
  (0, 1861)	0.07434740009253278
  (0, 3328)	0.0640745783502313
  (0, 3331)	0.08447124957013613
  :	:
  (49581, 4890)	0.10685497349746331
  (49581, 1540)	0.17578667665782954
  (49581, 4492)	0.09409901295390867
  (49581, 435)	0.11248913114654384
  (49581, 4275)	0.10907065013357405
  (49581, 1956)	0.09989194490412119
  (49581, 556)	0.08427028745995394
  (49581, 2186)	0.1417689189332931
  (49581, 2216)	0.09536996361688298
  (49581, 4345)	0.17503946863122663
  (49581, 4629)	0.11570028846900741
  (49581, 3646)	0.08738392277024566
  (49581, 4734)	0.12351111246282612
  (49581, 1975)	0.12792344102103054
  (49581, 528)	0.12478593347543351
  (49581, 2619)	0.17337130208285226
  (49581, 4457)	0.15998332561068096
  (49581, 2173)	0.18979170007191282
  (49581, 4032)	0.2009514508079407
  (49581, 342)	0.14781360314698977
  (49581, 2693)	0.1739656689734128
  (49581, 440)	0.13320278632182483
  (49581, 4980)	0.15092140777071886
  (49581, 1763)	0.15811460099655136
  (49581, 3488)	0.1520019194149111